meta_product_name: "Redore"
meta_title: "Recycle, Donate, Restore with Redore"
meta_description: "Book collections for your unwanted bulky waste items in just a few clicks"
meta_image: "redore_van.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
